### ISSUE TITLE
老铁 先给你点个大赞 不过建议重构下分模块设计/或是能不能用跨平台的GUI开发工具开发下Linux/Mac的

### ISSUE THREAD

**Issue by amazingchow** [HaujetZhao/QuickCut#10]

**Comment by HaujetZhao** [comment]
pyqt不是跨平台的 gui 吗？

**Comment by amazingchow** [comment]
pyqt没做过跨平台 个人建议electron会好一点

**Comment by HaujetZhao** [comment]
> pyqt没做过跨平台 个人建议electron会好一点

pyqt 真不能跨平台？

![23b318727dd9523c](https://user-images.githubusercontent.com/19181833/88920763-f75e3200-d29f-11ea-8645-0b82a52befbd.png)

<img width="375" alt="Thumb 6401146626791-e1f7db2e-863c-3a70-a05e-9a4ae3a5173c" src="https://user-images.githubusercontent.com/19181833/88921095-7eaba580-d2a0-11ea-8ab6-75259630e2e1.png">
