### ISSUE TITLE
历史记录

### ISSUE THREAD

**Issue by SplitGemini** [HaujetZhao/QuickCut#13]
记住路径等参数的历史设置，下次打开能够减少重复操作

**Comment by HaujetZhao** [comment]
good idea, no plan.

启动的时候要检察数据库好多条，关闭的时候要把好多条写入数据库。

选项框太多了，每个都要写的话，要累死。。。

其实为了解决这个问题，我在设置里做了 `点击关闭按钮时隐藏到托盘`  的选项，点击关闭就可以挂到托盘，省得下次再打开，还在重新弄参数。并且它的内存占用很小，挂后台不会影响性能。
