### ISSUE TITLE
Readme中的别字etc.

### ISSUE THREAD

**Issue by kynyka** [HaujetZhao/QuickCut#18]
> 这篇文章大部分都是用这个语音识别功能打的，然后修改了少量错字

 —— 既然这readme是由语音识别生成的，那咱就顺便将发现的几处不通顺的地方指出来好了：

1.  ... 应用之广泛**到惊了**我的下巴 --> 『**惊掉了**』？
2.  ... 上传音频便足**以**  -->  足『**矣**』
3.  ... 爽**的**不要不要的  -->  爽『**得**』
4.  ... 你们是~~你们~~觉得  -->  多了一次『**你们**』？
5.  ... 可以放心**的**放到后台  --> 放心『**地**』
6.  ... 在帮助**见面**里  --> 『**界面**』
7.  ... 直接到 这里 下载~~上~~它已经被志愿者  -->  多了个『**上**』？

**Comment by HaujetZhao** [comment]
已经修改
