### ISSUE TITLE
软件协议

### ISSUE THREAD

**Issue by VeleSila** [HaujetZhao/QuickCut#3]
这是一个很好的软件，也看得出来你花了很多心血。我非常希望20年后这个软件依旧有最基本的库/接口更新的维护。

没搞错的话你还是个学生，等你毕业可能会忙于生计。如果不冲突的话，建议把协议改成MPL之类的协议。虽然这在国内更像是君子协定，但是起码你也是对自己的努力作了一定保护，避免被无良公司或者公司的无良员工复制黏贴。说不定以后还能为你创造一笔收入（笑）。

加油喔~

**Comment by HaujetZhao** [comment]
> 这是一个很好的软件，也看得出来你花了很多心血。我非常希望20年后这个软件依旧有最基本的库/接口更新的维护。
> 
> 没搞错的话你还是个学生，等你毕业可能会忙于生计。如果不冲突的话，建议把协议改成MPL之类的协议。虽然这在国内更像是君子协定，但是起码你也是对自己的努力作了一定保护，避免被无良公司或者公司的无良员工复制黏贴。说不定以后还能为你创造一笔收入（笑）。
> 
> 加油喔~

好的，谢谢 ！
