### ISSUE TITLE
应该使用临时参数安装you-get和youtube-dl

### ISSUE THREAD

**Issue by SekiBetu** [HaujetZhao/QuickCut#36]
![image](https://user-images.githubusercontent.com/38283893/91717420-119f6e80-ebc4-11ea-9209-8e2fa0a800aa.png)
![image](https://user-images.githubusercontent.com/38283893/91717446-1b28d680-ebc4-11ea-88e1-673b5f9530c0.png)

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple you-get
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple youtube-dl

万一用户不想换源不能强制给他们换了啊🤣

**Comment by HaujetZhao** [comment]
已采纳 commit
