### ISSUE TITLE
建议 增加Google Web Speech API

### ISSUE THREAD

**Issue by shzxm** [HaujetZhao/QuickCut#4]
建议 
增加Google Web Speech API

原因
google的这个api是免费的

相关
下列开源项目有相关内容
https://github.com/agermanidis/autosub

**Comment by patui** [comment]
可以试试这个软件，目前完全免费https://github.com/patui/Nosub

**Comment by HaujetZhao** [comment]
我去看了下实现，谷歌语音识别变 并不能返回时间码 ，所以他转字幕其实是首先在本地通过声音预知将音频分割成片段 然后一段一段的去识别 。

然后在评论区看到有人说他这个识别分割片段不是太准确 ，找到了一个国人开发者的改进版，使用了新方法进行片段切割，在新版中还加入了百度引擎和讯飞引擎。

这样的话 要参考的东西实在太多了，我还有学业需要做，没有时间添加新的引擎了。

所以只能求助于志愿者了。用户暂时先使用阿里云的引擎吧。

**Comment by shzxm** [comment]
> 我去看了下实现，谷歌语音识别变而不能返回时间码，所以他转字幕其实是首先在本地通过声音预知将音频分割成片段然后一段一段的去识别。
> 
> 然后在评论区看到有人说他这个识别分割片段不是太准确，找到了一个国人开发者的改进版，使用了新方法进行片段切割，在新版中还加入了百度引擎和讯飞引擎。
> 
> 这样的话要参考的东西实在太多了，我还有学业需要做，没有时间添加新的引擎了。
> 
> 所以只能求助于志愿者了。用户暂时先使用阿里云的引擎吧。

好嘞~非常感谢考虑~
