### ISSUE TITLE
语音输入存在识别结果和输入结果不一致的问题

### ISSUE THREAD

**Issue by xp9388** [HaujetZhao/QuickCut#45]
利用语音输入功能进行输入时，发现控制台能够正确显示识别结果，但是光标写入word文件的是错误的结果
识别结果：
![image](https://user-images.githubusercontent.com/17606305/95822927-5be94300-0d5f-11eb-934a-344fbcf5aa54.png)

输入word文档结果：
![image](https://user-images.githubusercontent.com/17606305/95822981-73283080-0d5f-11eb-9d17-dafdedf69c28.png)

此问题目前仅发现出现在对word文件的输入上，时而正常、时而不正常
测试环境：win10 企业版 1909
测试软件：office 365 word
软件版本：V1.6.10

**Comment by HaujetZhao** [comment]
word 的问题。。。语音输入功能将会移出 QuickCut，请使用独立的 [CapsWriter](https://github.com/HaujetZhao/CapsWriter) 吧
