### ISSUE TITLE
「建议」开机自启动&启动最小化

### ISSUE THREAD

**Issue by rockbenben** [HaujetZhao/QuickCut#48]
阿里云的语音识别真的功能太棒了，主要用的是语音输入功能，希望开机后台常驻。

希望增加两个功能：
1. 开机自启动；
2. 启动自最小化。

**Comment by HaujetZhao** [comment]
这个功能的 bug 隐患比较多，之后会单独做成一个 app。开机启动就不做了，可以把快捷方式放到 `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` 里边

**Comment by rockbenben** [comment]
独立 APP 是 CapsWriter？期待后续的更新，希望独立应用能「启动最小化到图标」，直接常驻后台。

**Comment by HaujetZhao** [comment]
对，就是 CapsWriter 做上图形界面。此外，CapsWriter 要按下 Caps 键大约 1 秒后才能说话，我对此不满意，想做成按下去就开始录音，按下 Caps 就能开始说话，如果按的时长少于 0.5 秒，就不识别，删掉录音缓存，如果持续按下超过 0.5 秒，就开始识别。

**Comment by HaujetZhao** [comment]
[CapsWriter](https://github.com/HaujetZhao/CapsWriter)
