### ISSUE TITLE
建议增加对bilibili的预设参数支持

### ISSUE THREAD

**Issue by leavelet** [HaujetZhao/QuickCut#5]
b站的压制是硬需求
而小丸工具箱4年没有更新了
建议支持b站的参数
方便up主使用
bilibili的参数如下
![b站参数](https://i.loli.net/2020/07/29/DLQgE1CF3Mcl4fY.png)

**Comment by pzhlkj6612** [comment]
我来个文字版。

（复制自 [创作中心 - 哔哩哔哩弹幕视频网 - ( ゜- ゜)つロ 乾杯~](https://member.bilibili.com/v2#/upload/video) ，在 2020 年 07 月 29 日 13 时）

### 视频大小

- 网页端上传的文件大小上限为8G
- 视频内容时长最大10小时（提升电磁力，即可体验16G超大文件上限哦！前往创作实验室了解更多）

### 视频格式

- 网页端、桌面客户端推荐上传的格式为：mp4,flv（推荐上传的格式在转码过程更有优势，审核过程更快哦！）
- 其他允许上传的格式：mp4,flv,avi,wmv,mov,webm,mpeg4,ts,mpg,rm,rmvb,mkv,m4v

视频码率

- 视频码率建议20000kbps（H264/AVC编码）
- 视频峰值码率建议不超过60000kbps
- 音频码率最高320kbps（AAC编码）
- 分辨率最大支持4096x4096 120fps
- 关键帧平均至少10秒一个
- 色彩空间yuv420
- 位深8bit
- 声道数≤2
- 采样率=44100
- 逐行扫描

**Comment by HaujetZhao** [comment]
本来就支持。参数预设随便加。没有一个特别的  ffmpeg 参数可以说完美支持 bilibilib，用h264 那个预设就足矣。如果你有更好的 ffmpeg 输出选项，可以提出来。

**Comment by pzhlkj6612** [comment]
Hi ，我猜作者的意思**可能**是，请求添加一个预设，尽量去逼近 b 站的限制。这个预设应包含：

- 用`-b:a`、`-b:v`等参数设置（限制）音视频码率；
- 用`fps`滤镜或者`-r`参数设置（限制）帧率；
- 用`-pix_fmt`参数设置（限制）色彩空间，等等。

例如，在现在的“ H264\* ”预设的默认参数中，音频码率设置为 256 kbps （`-b:a 256k`）。那么，对于音频这个单项来说，所谓的“ b 站预设”就可以有不同的设置，从而与“ H264\* ”预设区分开。

另外，在这里我没有考虑“人对于 256 kbps 与 320 kbps 的音频流的实际体验的区别”这个问题，而仅仅是着眼于这些参数的设置和组合。

<br>

欢迎继续交流。

**Comment by cancundeyingzi** [comment]
> Hi ，我猜作者的意思**可能**是，请求添加一个预设，尽量去逼近 b 站的限制。这个预设应包含：
> 
> * 用`-b:a`、`-b:v`等参数设置（限制）音视频码率；
> * 用`fps`滤镜或者`-r`参数设置（限制）帧率；
> * 用`-pix_fmt`参数设置（限制）色彩空间，等等。
> 
> 例如，在现在的“ H264* ”预设的默认参数中，音频码率设置为 256 kbps （`-b:a 256k`）。那么，对于音频这个单项来说，所谓的“ b 站预设”就可以有不同的设置，从而与“ H264* ”预设区分开。
> 
> 另外，在这里我没有考虑“人对于 256 kbps 与 320 kbps 的音频流的实际体验的区别”这个问题，而仅仅是着眼于这些参数的设置和组合。
> 
> 
> 欢迎继续交流。

我倒是想知道,他这个预设能不能导入导出
