### ISSUE TITLE
建议增加批量处理选项

### ISSUE THREAD

**Issue by caseysui** [HaujetZhao/QuickCut#6]
首先感谢这么牛逼简单快速的软件。之前截取视频要几分钟，现在只要1秒，真的是1秒。
我经常会下载动画片然后去掉片头片尾的广告给我儿子看，能否给出个批量截取片段的功能。

**Comment by HaujetZhao** [comment]
好主意！没计划~做起来太复杂。

其实自动命令生成之后 你就可以把它拷贝下来 然后用其他的 批处理方法，将其中的文件名更换一下再运行。
