### ISSUE TITLE
[修改建议] `v1.8.0.Alpha` 标签与实际 Commit 不符（标签不在正确的分支和提交上）

### ISSUE THREAD

**Issue by Dragon1573** [HaujetZhao/QuickCut#80]
检查 [GitHub Releases](https://github.com/HaujetZhao/QuickCut/releases) ，注意到当前的最新版本是 [`v1.8.0.Alpha`](https://github.com/HaujetZhao/QuickCut/tree/v1.8.0.Alpha) ，与上一个版本 [`v1.6.10`](https://github.com/HaujetZhao/QuickCut/tree/v1.6.10) 指向的 Commit 是同一个，均为 https://github.com/HaujetZhao/QuickCut/commit/fffcd799c5ee6bb457dddbf0acfcbbea3522a36a 。将项目克隆至本地并检出标签 `v1.8.0.Alpha` ，在本地执行编译构建。编译生成后的主程序「帮助/关于」界面版本号仍为 `v1.6.10` 。

希望 @HaujetZhao 能够同步更新源代码，并将 `v1.8.0.Alpha` 上传至 PyPI 。

> Gitee 仓库存在此相同问题。

**Comment by HaujetZhao** [comment]
最新代码在 rebuild 这个分支，不在 master 分支。你切换一下，就看到了

因为还没有精力做详尽测试，就暂且还没合并到 master 分支。

**Comment by Dragon1573** [comment]
原来如此，要是能够更新并重标一下 `v1.8.0.Alpha` 这个标签对应的 Commit 会更好 🙏🏼

> 因为还没有精力做详尽测试，就暂且还没合并到 master 分支。

这样的话，是不是应该将这个 Tag 设置为 Pre-release 而不是 Stable release ？你目前的 Latest 标签是标在这个 Alpha 上的 😕

**Comment by Dragon1573** [comment]
看来重新标 Tag 并重发 Pre-release 比较麻烦……
