### ISSUE TITLE
点击下载链接后页面调整到广告

### ISSUE THREAD

**Issue by MackDing** [HaujetZhao/QuickCut#90]
![image](https://github.com/HaujetZhao/QuickCut/assets/19878893/3fc30dd4-adb7-40d7-977a-77ff4a284f21)

点击链接后页面调整到广告

![image](https://github.com/HaujetZhao/QuickCut/assets/19878893/afbc91c2-f0e9-47a9-9c90-a78c7dd9fba1)

**Comment by Love-OverFlow** [comment]
在最新的 Release 中的链接还能用，其中可以下载到测试版 `v1.8.0.Alpha`  和上一个稳定版 `v1.6.10`
> 下载
> Windows 64 位系统用户，到网盘下载「程序包」 7z 压缩包，解压，双击里面的 QuickCut.exe 就可以运行了。
> 
> 蓝奏云网盘：https://wwe.lanzoux.com/b015n2n5a 密码: f4t3

**Comment by MiunaQwQ** [comment]
把主域名lanzoux更改为lanzoui即可访问
